/**
 * Unit tests for the /api/yopu-search Cloudflare Pages Function.
 *
 * Run: node --test tests/functions/
 *
 * The codec vectors were generated by the Python reference (yopu-cli
 * yopu/codec.py); the raw body fixture is a captured live /z/ response, kept as
 * bytes so the XOR layer is exercised exactly as production sees it.
 */
import { test, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  encodeZ,
  decodeSearchResponse,
  normalizeYopuResults,
  onRequestGet,
  SOURCE_LIVE,
  SOURCE_LOCAL
} from "../../functions/api/yopu-search.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(HERE, "..", "fixtures");
const VECTORS = JSON.parse(fs.readFileSync(path.join(FIXTURES, "yopu_encode_z_vectors.json"), "utf8")).vectors;
const RAW_SEARCH = new Uint8Array(fs.readFileSync(path.join(FIXTURES, "yopu_search_raw.bin")));

const ORIGIN = "https://chord.example.test";
const REAL_FETCH = globalThis.fetch;

/** A fetch double that records every argument, including the ones no test reads yet. */
function installFetch(plan) {
  const calls = [];
  globalThis.fetch = async (input, init = {}) => {
    const url = String(input);
    calls.push({ url, init, headers: { ...(init.headers || {}) } });
    return plan(url, init);
  };
  return calls;
}

function jsonResponse(obj, status = 200) {
  return new Response(JSON.stringify(obj), { status, headers: { "content-type": "application/json" } });
}

const EXPLORE_OK = () => new Response("", { headers: { "set-cookie": "c=abc123; Max-Age=31536000; Path=/; HttpOnly" } });

const MODERN_CORPUS = [
  {
    id: "modern_a",
    title: "再见青春",
    artist: "汪峰",
    key: "C major",
    capo: 0,
    primary_progression: "6,4,1,5",
    primary_roman: "vi-IV-I-V",
    primary_chords: ["Am", "F", "C", "G"],
    source_url: "https://yopu.co/view/3PbL9Wr1"
  },
  { id: "modern_b", title: "晴天", artist: "周杰伦", key: "G major", primary_progression: "1,5,6,4" }
];
const CURATED_CORPUS = [
  { id: "zh_1", title: "存在", artist: "汪峰 (Wang Feng)", key: "C major", progression: "1,5,6,4", roman: "I-V-vi-IV", chords: ["C", "G", "Am", "F"] }
];

function corpusPlan(url) {
  if (url === `${ORIGIN}/data/chinese_modern_corpus.json`) return jsonResponse(MODERN_CORPUS);
  if (url === `${ORIGIN}/data/chinese_corpus.json`) return jsonResponse(CURATED_CORPUS);
  return null;
}

async function call(query) {
  const resp = await onRequestGet({ request: new Request(`${ORIGIN}/api/yopu-search?${query}`) });
  return { resp, body: await resp.json() };
}

beforeEach(() => {
  globalThis.fetch = REAL_FETCH;
});
afterEach(() => {
  globalThis.fetch = REAL_FETCH;
});

test("encodeZ matches the Python reference for every pinned vector", () => {
  assert.ok(VECTORS.length >= 6, `degenerate vector set: ${VECTORS.length}`);
  for (const v of VECTORS) assert.equal(encodeZ(v.path), v.z, v.path);
  console.log(`graded ${VECTORS.length} encode_z vectors`);
});

test("decodeSearchResponse decodes a captured live /z/ body", () => {
  const data = decodeSearchResponse(RAW_SEARCH);
  assert.equal(data.totalResultNum, 23);
  assert.equal(data.results.length, 10);
  assert.equal(data.results[0].entryType, "song");
  const rows = normalizeYopuResults(data);
  assert.equal(rows.length, 14);
  assert.ok(rows.every((r) => r.source === SOURCE_LIVE && r.url.startsWith("https://yopu.co/view/")));
  assert.ok(rows.some((r) => r.title.includes("再见青春")));
});

test("live path: session cookie from /explore is sent to the /z/ URL and results are tagged yopu_live", async () => {
  const vector = VECTORS.find((v) => v.q === "再见青春" && v.page === 0 && v.instrument === "guitar");
  const calls = installFetch((url) => {
    if (url === "https://yopu.co/explore") return EXPLORE_OK();
    if (url === `https://yopu.co${vector.z}`) return new Response(RAW_SEARCH);
    throw new Error(`unexpected fetch ${url}`);
  });

  const { resp, body } = await call("q=%E5%86%8D%E8%A7%81%E9%9D%92%E6%98%A5");

  assert.equal(resp.status, 200);
  assert.equal(body.source, SOURCE_LIVE);
  assert.equal(body.total, 23);
  assert.equal(body.results.length, 14);
  assert.equal(resp.headers.get("cache-control"), "public, max-age=1800");
  assert.equal(calls.length, 2, "exactly /explore then /z/");
  assert.equal(calls[1].url, `https://yopu.co${vector.z}`);
  assert.equal(calls[1].headers.Cookie, "c=abc123");
  assert.equal(calls[1].headers.Referer, "https://yopu.co/explore");
  assert.equal(calls[0].headers.Cookie, undefined, "init request carries no cookie");
});

test("blocked path: empty 404 from /z/ falls back to the bundled corpora, tagged local_corpus, uncached", async () => {
  installFetch((url) => {
    if (url === "https://yopu.co/explore") return EXPLORE_OK();
    if (url.startsWith("https://yopu.co/z/")) return new Response("", { status: 404 });
    return corpusPlan(url) || new Response("", { status: 404 });
  });

  const { resp, body } = await call("q=%E6%B1%AA%E5%B3%B0");

  assert.equal(resp.status, 200);
  assert.equal(body.source, SOURCE_LOCAL);
  assert.equal(resp.headers.get("cache-control"), "no-store");
  assert.match(body.upstream_error, /empty HTTP 404/);
  assert.ok(body.note && body.note.length > 0);
  assert.equal(body.error, undefined, "matches found, so no error field");
  assert.deepEqual(
    body.results.map((r) => [r.title, r.corpus, r.progression]),
    [["再见青春", "chinese_modern", "6,4,1,5"], ["存在", "chinese_curated", "1,5,6,4"]]
  );
  assert.ok(body.results.every((r) => r.verified === false), "local rows never claim Yopu verification");
});

test("fallback requires every query token to match title or artist", async () => {
  installFetch((url) => {
    if (url === "https://yopu.co/explore") throw new TypeError("fetch failed");
    return corpusPlan(url) || new Response("", { status: 404 });
  });

  const { body } = await call("q=%E6%B1%AA%E5%B3%B0%20%E5%AD%98%E5%9C%A8"); // 汪峰 存在

  assert.equal(body.source, SOURCE_LOCAL);
  assert.equal(body.upstream_error, "fetch failed");
  assert.deepEqual(body.results.map((r) => r.title), ["存在"]);
});

test("upstream failure with no local match reports the cause instead of a bare empty list", async () => {
  installFetch((url) => {
    if (url === "https://yopu.co/explore") return EXPLORE_OK();
    if (url.startsWith("https://yopu.co/z/")) return new Response("nope", { status: 503 });
    return corpusPlan(url) || new Response("", { status: 404 });
  });

  const { body } = await call("q=zzz-no-such-song");

  assert.equal(body.source, SOURCE_LOCAL);
  assert.equal(body.results.length, 0);
  assert.match(body.upstream_error, /HTTP 503/);
  assert.match(body.error, /HTTP 503/);
});

test("empty query never touches the network", async () => {
  const calls = installFetch(() => {
    throw new Error("must not fetch");
  });

  const { resp, body } = await call("q=%20%20");

  assert.equal(resp.status, 200);
  assert.deepEqual(body.results, []);
  assert.equal(calls.length, 0);
});
